### ISSUE TITLE
Airbrake logging an unexpected 500 response from Airbrake API

### ISSUE THREAD

**Issue by scottsbaldwin** [airbrake/airbrake-ruby#696] opened 2022-08-17 14:10 UTC
Hi Airbrake team! I have noticed that the `airbrake` gem (actually, `airbrake-ruby`) is logging a message in my application logs that it is receiving an HTTP 500 from the Airbrake API. My logs include only a truncated body so I can't give you more than this. I have seen two log messages related to the 500 errors:

```
E, [2022-08-17T14:02:09.374595 #7] ERROR -- : **Airbrake: unexpected code (500). Body: <html>
  <!--<![endif]-->
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible"...
```

and

```
E, [2022-08-17T10:51:53.197554 #7] ERROR -- : **Airbrake: unexpected code (500). Body: {"code":500,"type":"Internal Server Error","message":"An error occurred while processing your request...
```

It appears that this message is written by https://github.com/airbrake/airbrake-ruby/blob/dfd766fc688c55741e3e8b98fa5ac7ba1fbc4c48/lib/airbrake-ruby/response.rb#L47. I am seeing these log messages every 30-60 seconds.

**Comment by Penthious** [comment] 2022-08-17 16:25
Looking into this, thank you

**Comment by shiva-gautam** [comment] 2022-08-18 13:23
We too are facing the same issue with truncated body message in our application logs.
` [Airbrake] [3]: unexpected code (500). Body: <html>#012  <!--<![endif]-->#012  <head>#012    <meta charset="utf-8"/>#012    <meta http-equiv="X-UA-Compatible"...`

**Comment by williantenfen** [comment] 2022-08-18 14:59
same here!

**Comment by lessarderic** [comment] 2022-08-22 15:25
@Penthious, any ETA on a fix? This is causing us some problems in production right now and limiting our ability to use Airbrake.

**Comment by Penthious** [comment] 2022-08-22 16:47
> @Penthious, any ETA on a fix? This is causing us some problems in production right now and limiting our ability to use Airbrake.

Our team is currently looking into this error, it is not a notifier issue hence why the ticket was closed. When the issue is resolved on our end I'll make sure to ping you here as well.

**Comment by EvNomad** [comment] 2022-08-24 12:56
Waiting for the fix as well. Thanks!

**Comment by rodrizapico** [comment] 2022-08-24 13:46
Just to add to this, since we're also running into this issue, we're seeing the following error logs in addition to the ones already reported:

`[0;35m2022-08-24 13:12:13.755[0m [31mERROR[0m **Airbrake: HTTP error: end of file reached`

And 

`[0;35m2022-08-24 13:15:17.414[0m [31mERROR[0m **Airbrake: HTTP error: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A`

This is happening both in a Ruby 2.3 instance running and old version of the notifier, and a Ruby 2.7 instance running the latest version (6.1.1).

**Comment by mmcdaris** [comment] 2022-09-01 17:18
Thank you all for your patience on this one 🙏❤️ We believe our latest fix was successful, can you please confirm on your side?

**Comment by arfelio** [comment] 2022-09-01 17:39
> Thank you all for your patience on this one 🙏❤️ We believe our latest fix was successful, can you please confirm on your side?

Hi do you mean version 6.1.2 ?

**Comment by kyrylo** [comment] 2022-09-02 07:39
@arfelio 6.1.2 won't fix the problem. The issue is not with airbrake-ruby, as it's not a library bug. We've been keeping this issue open so that others can communicate with us in one place, but strictly speaking, this ticket shouldn't exist in this repo.

As @mmcdaris mentioned, we've made some internal tweaks that should resolve the problem.

**Closed by kyrylo** 2022-09-02 07:39 UTC
Labels: Question

**Comment by arfelio** [comment] 2022-09-02 15:06
@kyrylo i updated to the last versions of airbrake and airbrake-ruby yesterday, and today i hadn't such errors all day. Seems it works fine. Thank you

**Comment by scottsbaldwin** [comment] 2022-09-06 20:28
@kyrylo, @mmcdaris, @Penthious thanks for the fixes!!! ❤️
