### ISSUE TITLE
AWS Lambda Ruby 2.7

### ISSUE THREAD

**Issue by lloydpick** [airbrake/airbrake-ruby#630] opened 2020-11-12 17:05 UTC
Hi,

I've been trying to get Airbrake into an AWS Lambda on Ruby 2.7, however it seems that the second the `Airbrake.configure` block is called, it crashes out with...

```
{
  "errorMessage": "wrong number of arguments (given 9, expected 1..3)",
  "errorType": "Init<ArgumentError>",
  "stackTrace": [
    "/var/lang/lib/ruby/2.7.0/logger.rb:379:in `initialize'"
  ]
}
```

I've attached a zip of a Lambda, which only has the Airbrake gem installed, so it can be reproduced.

[airbrake.zip](https://github.com/airbrake/airbrake-ruby/files/5532081/airbrake.zip)

**Comment by kyrylo** [comment] 2020-11-13 06:08
Hey there,

Are you sure it's Airbrake that is the problem here? I can reproduce your issue like this:


```
> Logger.new(1,2,3,4,5,6,7,8,9)
ArgumentError: wrong number of arguments (given 9, expected 1..3)
from /Users/kyrylo/.rubies/ruby-2.7.1/lib/ruby/2.7.0/logger.rb:379:in `initialize'
```

If you don't pass a logger in the `configure` block, the default logger will be used. You can try to pass the logger that you created to see if it helps:

```
Airbrake.configure do |c|
  c.project_id = ENV['AIRBRAKE_PROJECT_ID']
  c.project_key = ENV['AIRBRAKE_PROJECT_KEY']
  c.logger = LOG
end
```

**Comment by lloydpick** [comment] 2020-11-13 15:40
Ok, so after some more digging this is an issue caused by AWS in their Ruby 2.7 runtime. They monkeypatch Logger for logs written to `STDOUT` and `STDERR`, however in Airbrakes case it's trying to use `File:NULL`...

https://github.com/airbrake/airbrake-ruby/blob/ffe87c0bbe39bc34fff6f07a4ad9b56324403edf/lib/airbrake-ruby/config.rb#L149

So it wouldn't use their patch, however when AWS decides to use the original initializer they make the wrong call. Basically they pass all arguments as normal arguments, rather than the mix that Logger wants of some normal arguments and some named arguments.

I've raised the issue with AWS. So I'll just have to wait for them to fix it, as even if I send my own logger into Airbrake, it'll still try to initialize the one for `File::NULL` as the users overrides only get applied afterwards it looks like.

**Comment by kyrylo** [comment] 2020-11-16 07:44
Thanks for clarifying this. It will be useful for anyone who stumbles upon the same issue. I'm going to close this issue because it looks like there's not much for us to do here. We don't want to change the default behavior.

**Closed by kyrylo** 2020-11-16 07:44 UTC
Labels: Question
